apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: dotnetcore
spec:
  template:
    metadata:
      labels:
        app: dotnetcore
        tier: web
    spec:
      containers:
      - name: dotnetcore-app
        image: johnnybouder/dotnetcore-website
        ports:
        - containerPort: 8080